### ISSUE TITLE
image check failed error

### ISSUE THREAD

**Issue by maxmib** [darkxst/erx-migration#5]
After  updating my er-x with your scripts，I try to  upgrade openwrt through luci web ,it shows image check failed error, but after force upgrade ,er-x seems to work well.

 error log :
Fri Dec 6 21:27:27 CST 2024 upgrade: The device is supported, but this image is incompatible for sysupgrade based on the image version (1.1->2.0). 
Fri Dec 6 21:27:27 CST 2024 upgrade: Partition table has been changed due to kernel size restrictions. Refer to the wiki page for instructions to migrate to the new layout: https://openwrt.org/toh/ubiquiti/edgerouter_x_er-x_ka Image check failed.

Is this normal ?Any idea to solve this ? Thanks

**Comment by darkxst** [comment]
This is strange, the compat level is set to 2.0 in the new rootfs, the only way to retain the old 1.1 compat level is to force a sysupgrade with keeping old settings. However this is not possible with the migration script, that will always wipe all settings.

Check the partition layout has picked up new format as per below.
```
root@OpenWrt:/# cat /proc/mtd
dev:    size   erasesize  name
mtd0: 00080000 00020000 "u-boot"
mtd1: 00060000 00020000 "u-boot-env"
mtd2: 00060000 00020000 "factory"
mtd3: 00600000 00020000 "kernel"
mtd4: 0f7c0000 00020000 "ubi"
```
Make sure /lib/upgrade/ubnt.sh is up to date with this:
https://github.com/openwrt/openwrt/blob/openwrt-24.10/target/linux/ramips/mt7621/base-files/lib/upgrade/ubnt.sh


IF you are absolutely sure the new 24.10rc is installed and everything correct you can update compat manually

```sh
uci  set system.@system[0].compat_version=2.0
uci commit
```

EDIT on second thoughts if you restored a backup after migration, maybe the wrong setting came from the backup. If that was the case, just update compat manually it should be safe.

**Comment by maxmib** [comment]
> This is strange, the compat level is set to 2.0 in the new rootfs, the only way to retain the old 1.1 compat level is to force a sysupgrade with keeping old settings. However this is not possible with the migration script, that will always wipe all settings.
> 
> Check the partition layout has picked up new format as per below.
> 
> ```
> root@OpenWrt:/# cat /proc/mtd
> dev:    size   erasesize  name
> mtd0: 00080000 00020000 "u-boot"
> mtd1: 00060000 00020000 "u-boot-env"
> mtd2: 00060000 00020000 "factory"
> mtd3: 00600000 00020000 "kernel"
> mtd4: 0f7c0000 00020000 "ubi"
> ```
> 
> Make sure /lib/upgrade/ubnt.sh is up to date with this: https://github.com/openwrt/openwrt/blob/openwrt-24.10/target/linux/ramips/mt7621/base-files/lib/upgrade/ubnt.sh
> 
> IF you are absolutely sure the new 24.10rc is installed and everything correct you can update compat manually
> 
> ```shell
> uci  set system.@system[0].compat_version=2.0
> uci commit
> ```
> 
> EDIT on second thoughts if you restored a backup after migration, maybe the wrong setting came from the backup. If that was the case, just update compat manually it should be safe.

Yes,I retored backup after migration ,and I checked the partition layout ,it's in new format.So I updated compat manually as you suggested. Then image check failed error disappeard. Thanks a lot.

**Comment by KsmoinO** [comment]
Hello

I had the same issue after restoring backup. Maybe add a note on the readme about the system.@system[0].compat_version value.

Thanks
